# Gun configuration data for PECC system
# Add or update gun configs as needed

gun_configs = {
    "GUN1": {
        "firmwareVersion": "pe_1.0.2",
        "manufacturer": "ultrafastchargers_pvt_ltd",
        "limitVoltageMin": 0,
        "limitVoltageMax": 100,
        "limitCurrentMin": 0,
        "limitCurrentMax": 50,
        "limitPowerMin": 0,
        "limitPowerMax": 120000,
        "limitDischargeCurrentMin": 0,
        "limitDischargeCurrentMax": -30,
        "limitDischargePowerMin": 0,
        "limitDischargePowerMax": -15000,
        "floatValues": True
    },
    "GUN2": {
        "firmwareVersion": "pe_1.0.2",
        "manufacturer": "ultrafastchargers_pvt_ltd",
        "limitVoltageMin": 0,
        "limitVoltageMax": 200,
        "limitCurrentMin": 0,
        "limitCurrentMax": 60,
        "limitPowerMin": 0,
        "limitPowerMax": 35000,
        "limitDischargeCurrentMin": 0,
        "limitDischargeCurrentMax": -40,
        "limitDischargePowerMin": 0,
        "limitDischargePowerMax": -20000,
        "floatValues": True
    },
    "GUN3": {
        "firmwareVersion": "pe_1.0.2",
        "manufacturer": "ultrafastchargers_pvt_ltd",
        "limitVoltageMin": 0,
        "limitVoltageMax": 300,
        "limitCurrentMin": 0,
        "limitCurrentMax": 60,
        "limitPowerMin": 0,
        "limitPowerMax": 35000,
        "limitDischargeCurrentMin": 0,
        "limitDischargeCurrentMax": -40,
        "limitDischargePowerMin": 0,
        "limitDischargePowerMax": -20000,
        "floatValues": True
    },
    "GUN4": {
        "firmwareVersion": "pe_1.0.2",
        "manufacturer": "ultrafastchargers_pvt_ltd",
        "limitVoltageMin": 0,
        "limitVoltageMax": 400,
        "limitCurrentMin": 0,
        "limitCurrentMax": 60,
        "limitPowerMin": 0,
        "limitPowerMax": 35000,
        "limitDischargeCurrentMin": 0,
        "limitDischargeCurrentMax": -40,
        "limitDischargePowerMin": 0,
        "limitDischargePowerMax": -20000,
        "floatValues": True
    },
    "GUN5": {
        "firmwareVersion": "pe_1.0.2",
        "manufacturer": "ultrafastchargers_pvt_ltd",
        "limitVoltageMin": 0,
        "limitVoltageMax": 500,
        "limitCurrentMin": 0,
        "limitCurrentMax": 60,
        "limitPowerMin": 0,
        "limitPowerMax": 35000,
        "limitDischargeCurrentMin": 0,
        "limitDischargeCurrentMax": -40,
        "limitDischargePowerMin": 0,
        "limitDischargePowerMax": -20000,
        "floatValues": True
    },
    "GUN6": {
        "firmwareVersion": "pe_1.0.2",
        "manufacturer": "ultrafastchargers_pvt_ltd",
        "limitVoltageMin": 0,
        "limitVoltageMax": 600,
        "limitCurrentMin": 0,
        "limitCurrentMax": 60,
        "limitPowerMin": 0,
        "limitPowerMax": 35000,
        "limitDischargeCurrentMin": 0,
        "limitDischargeCurrentMax": -40,
        "limitDischargePowerMin": 0,
        "limitDischargePowerMax": -20000,
        "floatValues": True
    },
    "GUN7": {
        "firmwareVersion": "pe_1.0.2",
        "manufacturer": "ultrafastchargers_pvt_ltd",
        "limitVoltageMin": 0,
        "limitVoltageMax": 700,
        "limitCurrentMin": 0,
        "limitCurrentMax": 60,
        "limitPowerMin": 0,
        "limitPowerMax": 35000,
        "limitDischargeCurrentMin": 0,
        "limitDischargeCurrentMax": -40,
        "limitDischargePowerMin": 0,
        "limitDischargePowerMax": -20000,
        "floatValues": True
    },
    "GUN8": {
        "firmwareVersion": "pe_1.0.2",
        "manufacturer": "ultrafastchargers_pvt_ltd",
        "limitVoltageMin": 0,
        "limitVoltageMax": 800,
        "limitCurrentMin": 0,
        "limitCurrentMax": 60,
        "limitPowerMin": 0,
        "limitPowerMax": 35000,
        "limitDischargeCurrentMin": 0,
        "limitDischargeCurrentMax": -40,
        "limitDischargePowerMin": 0,
        "limitDischargePowerMax": -20000,
        "floatValues": True
    },
    "GUN9": {
        "firmwareVersion": "pe_1.0.2",
        "manufacturer": "ultrafastchargers_pvt_ltd",
        "limitVoltageMin": 0,
        "limitVoltageMax": 900,
        "limitCurrentMin": 0,
        "limitCurrentMax": 60,
        "limitPowerMin": 0,
        "limitPowerMax": 35000,
        "limitDischargeCurrentMin": 0,
        "limitDischargeCurrentMax": -40,
        "limitDischargePowerMin": 0,
        "limitDischargePowerMax": -20000,
        "floatValues": True
    },
    "GUN10": {
        "firmwareVersion": "pe_1.0.2",
        "manufacturer": "ultrafastchargers_pvt_ltd",
        "limitVoltageMin": 0,
        "limitVoltageMax": 1000,
        "limitCurrentMin": 0,
        "limitCurrentMax": 60,
        "limitPowerMin": 0,
        "limitPowerMax": 35000,
        "limitDischargeCurrentMin": 0,
        "limitDischargeCurrentMax": -40,
        "limitDischargePowerMin": 0,
        "limitDischargePowerMax": -20000,
        "floatValues": True
    },
    "GUN11": {
        "firmwareVersion": "pe_1.0.2",
        "manufacturer": "ultrafastchargers_pvt_ltd",
        "limitVoltageMin": 0,
        "limitVoltageMax": 1100,
        "limitCurrentMin": 0,
        "limitCurrentMax": 60,
        "limitPowerMin": 0,
        "limitPowerMax": 35000,
        "limitDischargeCurrentMin": 0,
        "limitDischargeCurrentMax": -40,
        "limitDischargePowerMin": 0,
        "limitDischargePowerMax": -20000,
        "floatValues": True
    },
    "GUN12": {
        "firmwareVersion": "pe_1.0.2",
        "manufacturer": "ultrafastchargers_pvt_ltd",
        "limitVoltageMin": 0,
        "limitVoltageMax": 1200,
        "limitCurrentMin": 0,
        "limitCurrentMax": 60,
        "limitPowerMin": 0,
        "limitPowerMax": 35000,
        "limitDischargeCurrentMin": 0,
        "limitDischargeCurrentMax": -40,
        "limitDischargePowerMin": 0,
        "limitDischargePowerMax": -20000,
        "floatValues": True
    },
}


# class communication_model:
#     {"info": {
#         "request": {
#             "configuration" : gun_configs.get("GUN12"),
#             "cablecheck"    : {},
#             "targetVAlue"    : {
#                 "targetVoltage" : DATA_MODEL.getVolatge("GUN1"),
#             },
#         }
#     },
#         "response": {
#             "configuration" : gun_configs.get("GUN12"),
#             "cablecheck"    : {},
#         }
#     }
