# Gun configuration data for PECC system
# Add or update gun configs as needed

gun_configs = {
    "GUN1": {
        "firmwareVersion": "pe_1.0.2",
        "manufacturer": "ultrafastchargers_pvt_ltd",
        "limitVoltageMin": 0,
        "limitVoltageMax": 1000,
        "limitCurrentMin": 0,
        "limitCurrentMax": 250,
        "limitPowerMin": 0,
        "limitPowerMax": 30000,
        "limitDischargeCurrentMin": 0,
        "limitDischargeCurrentMax": -30,
        "limitDischargePowerMin": 0,
        "limitDischargePowerMax": -15000,
        "floatValues": True
    },
    "GUN2": {
        "firmwareVersion": "pe_1.0.2",
        "manufacturer": "ultrafastchargers_pvt_ltd",
        "limitVoltageMin": 0,
        "limitVoltageMax": 1000,
        "limitCurrentMin": 0,
        "limitCurrentMax":  250,
        "limitPowerMin": 0,
        "limitPowerMax": 60000,
        "limitDischargeCurrentMin": 0,
        "limitDischargeCurrentMax": -40,
        "limitDischargePowerMin": 0,
        "limitDischargePowerMax": -20000,
        "floatValues": True
    },
    "GUN3": {
        "firmwareVersion": "pe_1.0.2",
        "manufacturer": "ultrafastchargers_pvt_ltd",
        "limitVoltageMin": 0,
        "limitVoltageMax": 1000,
        "limitCurrentMin": 0,
        "limitCurrentMax":  250,
        "limitPowerMin": 0,
        "limitPowerMax": 90000,
        "limitDischargeCurrentMin": 0,
        "limitDischargeCurrentMax": -40,
        "limitDischargePowerMin": 0,
        "limitDischargePowerMax": -20000,
        "floatValues": True
    },
    "GUN4": {
        "firmwareVersion": "pe_1.0.2",
        "manufacturer": "ultrafastchargers_pvt_ltd",
        "limitVoltageMin": 0,
        "limitVoltageMax": 1000,
        "limitCurrentMin": 0,
        "limitCurrentMax":  250,
        "limitPowerMin": 0,
        "limitPowerMax": 10000,
        "limitDischargeCurrentMin": 0,
        "limitDischargeCurrentMax": -40,
        "limitDischargePowerMin": 0,
        "limitDischargePowerMax": -20000,
        "floatValues": True
    },
    "GUN5": {
        "firmwareVersion": "pe_1.0.2",
        "manufacturer": "ultrafastchargers_pvt_ltd",
        "limitVoltageMin": 0,
        "limitVoltageMax": 1000,
        "limitCurrentMin": 0,
        "limitCurrentMax": 250,
        "limitPowerMin": 0,
        "limitPowerMax": 150000,
        "limitDischargeCurrentMin": 0,
        "limitDischargeCurrentMax": -40,
        "limitDischargePowerMin": 0,
        "limitDischargePowerMax": -20000,
        "floatValues": True
    },
    "GUN6": {
        "firmwareVersion": "pe_1.0.2",
        "manufacturer": "ultrafastchargers_pvt_ltd",
        "limitVoltageMin": 0,
        "limitVoltageMax": 1000,
        "limitCurrentMin": 0,
        "limitCurrentMax": 250,
        "limitPowerMin": 0,
        "limitPowerMax": 180000,
        "limitDischargeCurrentMin": 0,
        "limitDischargeCurrentMax": -40,
        "limitDischargePowerMin": 0,
        "limitDischargePowerMax": -20000,
        "floatValues": True
    },
    "GUN7": {
        "firmwareVersion": "pe_1.0.2",
        "manufacturer": "ultrafastchargers_pvt_ltd",
        "limitVoltageMin": 0,
        "limitVoltageMax": 1000,
        "limitCurrentMin": 0,
        "limitCurrentMax":  250,
        "limitPowerMin": 0,
        "limitPowerMax": 210000,
        "limitDischargeCurrentMin": 0,
        "limitDischargeCurrentMax": -40,
        "limitDischargePowerMin": 0,
        "limitDischargePowerMax": -20000,
        "floatValues": True
    },
    "GUN8": {
        "firmwareVersion": "pe_1.0.2",
        "manufacturer": "ultrafastchargers_pvt_ltd",
        "limitVoltageMin": 0,
        "limitVoltageMax": 1000,
        "limitCurrentMin": 0,
        "limitCurrentMax":  250,
        "limitPowerMin": 0,
        "limitPowerMax": 240000,
        "limitDischargeCurrentMin": 0,
        "limitDischargeCurrentMax": -40,
        "limitDischargePowerMin": 0,
        "limitDischargePowerMax": -20000,
        "floatValues": True
    },
    "GUN9": {
        "firmwareVersion": "pe_1.0.2",
        "manufacturer": "ultrafastchargers_pvt_ltd",
        "limitVoltageMin": 0,
        "limitVoltageMax": 1000,
        "limitCurrentMin": 0,
        "limitCurrentMax":  250,
        "limitPowerMin": 0,
        "limitPowerMax": 270000,
        "limitDischargeCurrentMin": 0,
        "limitDischargeCurrentMax": -40,
        "limitDischargePowerMin": 0,
        "limitDischargePowerMax": -20000,
        "floatValues": True
    },
    "GUN10": {
        "firmwareVersion": "pe_1.0.2",
        "manufacturer": "ultrafastchargers_pvt_ltd",
        "limitVoltageMin": 0,
        "limitVoltageMax": 1000,
        "limitCurrentMin": 0,
        "limitCurrentMax":  250,
        "limitPowerMin": 0,
        "limitPowerMax": 300000,
        "limitDischargeCurrentMin": 0,
        "limitDischargeCurrentMax": -40,
        "limitDischargePowerMin": 0,
        "limitDischargePowerMax": -20000,
        "floatValues": True
    },
    "GUN11": {
        "firmwareVersion": "pe_1.0.2",
        "manufacturer": "ultrafastchargers_pvt_ltd",
        "limitVoltageMin": 0,
        "limitVoltageMax": 1000,
        "limitCurrentMin": 0,
        "limitCurrentMax":  250,
        "limitPowerMin": 0,
        "limitPowerMax": 330000,
        "limitDischargeCurrentMin": 0,
        "limitDischargeCurrentMax": -40,
        "limitDischargePowerMin": 0,
        "limitDischargePowerMax": -20000,
        "floatValues": True
    },
    "GUN12": {
        "firmwareVersion": "pe_1.0.2",
        "manufacturer": "ultrafastchargers_pvt_ltd",
        "limitVoltageMin": 0,
        "limitVoltageMax": 1000,
        "limitCurrentMin": 0,
        "limitCurrentMax":  250,
        "limitPowerMin": 0,
        "limitPowerMax": 360000,
        "limitDischargeCurrentMin": 0,
        "limitDischargeCurrentMax": -40,
        "limitDischargePowerMin": 0,
        "limitDischargePowerMax": -20000,
        "floatValues": True
    },
}


# class communication_model:
#     {"info": {
#         "request": {
#             "configuration" : gun_configs.get("GUN12"),
#             "cablecheck"    : {},
#             "targetVAlue"    : {
#                 "targetVoltage" : DATA_MODEL.getVolatge("GUN1"),
#             },
#         }
#     },
#         "response": {
#             "configuration" : gun_configs.get("GUN12"),
#             "cablecheck"    : {},
#         }
#     }
